lending_library/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls')),
]

products/urls.py
"""Defines url patterns for products."""

from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),

    # Show all products.
    path('products/', views.products, name='products'),

    # Detail page for a single product.
    path('products/<int:product_id>/', views.product, name='product'),

    # Page for adding a new product
    path('products/new_product/', views.new_product, name='new_product'),

    # MyProducts
    path('myproducts/', views.my_products, name='my_products'),

    # Page for borrowing a product
    path('borrow_product/<int:product_id>/', views.borrow_product, name='borrow_product'),

]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
	# Login page.
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    # Logout page.
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Registration page
    path('register/', views.register, name='register'),

]

products/models.py
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
	"""A product the user wants to list."""
	text = models.CharField(max_length=200)
	date_added = models.DateTimeField(auto_now_add=True)
	PRODUCT_TYPE_CHOICES = [
		('Book', 'Book'),
		('Tool', 'Tool'),
		('Service', 'Service'),
	]

	product_type = models.CharField(
		max_length=20,
		choices=PRODUCT_TYPE_CHOICES,
		default='Book',
		)

	description = models.TextField(default='')
	owner = models.ForeignKey(User, on_delete=models.CASCADE)
	# borrower = models.ForeignKey(Borrower, on_delete=models.CASCADE)
	
	def __str__(self):
		"""Return a string representation of the model."""
		return self.text

class Entry(models.Model):
	"""Something specific to discuss about a book/product."""
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	text = models.TextField()
	date_added = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = 'entries'

	def __str__(self):
		"""Return a string representation of the model."""
		return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

products/forms.py
from django import forms 

from .models import Product

class ProductForm(forms.ModelForm):
	class Meta:
		model = Product
		fields = ['text', 'product_type', 'description']
		labels = {'text': ''}

products/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse 
from django.contrib.auth.decorators import login_required

from .models import Product
from .forms import ProductForm

def index(request):
	"""The home page for Lending Library"""
	return render(request, 'products/index.html')

def products(request):
	"""Show all products."""
	products = Product.objects.order_by('-date_added')
	context = {'products': products}
	return render(request, 'products/products.html', context)

def product(request, product_id):
	"""Show a single product and all of its fields."""
	product = Product.objects.get(id=product_id)
	entries = product.entry_set.order_by('-date_added')
	context = {'product': product, 'entries': entries}
	return render(request, 'products/product.html', context)

@login_required
def new_product(request):
	"""Add a new product."""
	if request.method != 'POST':
		# No data submitted; create a blank form.
		form = ProductForm()
	else:
		# POST data submitted; process data.
		form = ProductForm(request.POST)
		if form.is_valid():
			new_product = form.save(commit=False)
			new_product.owner = request.user
			new_product.save()
			return HttpResponseRedirect(reverse('products:products'))

	context = {'form': form}
	return render(request, 'products/new_product.html', context)

@login_required
def my_products(request):
	"""Show all of a user's products."""
	products = Product.objects.filter(owner=request.user).order_by('date_added')
	context = {'products': products}
	return render(request, 'products/my_products.html', context)

def borrow_product(request, product_id):
	"""Borrow a product."""
	product = Product.objects.get(id=product_id)

	if request.method != 'POST':
		# Initial request; pre-fill form with the current product info.
		form = ProductForm(instance=product)
	else:
		# POST data submitted; process data.
		form = ProductForm(instance=product, data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('products:product', args=[product.id])) 

	context = {'product': product, 'form': form}
	return render(request, 'products/borrow_product.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
	"""Log the user out."""
	logout(request)
	return HttpResponseRedirect(reverse('products:index'))

def register(request):
	"""Register a new user."""
	if request.method != 'POST':
		# Display blank registration form.
		form = UserCreationForm()
	else:
		# Process completed form.
		form = UserCreationForm(data=request.POST)

		if form.is_valid():
			new_user = form.save()
			# Log the user in and then redirect to home page.
			authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
			login(request, authenticated_user)
			return HttpResponseRedirect(reverse('products:index'))

	context = {'form': form}
	return render(request, 'users/register.html', context)

products/templates/products/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Lending Library</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'products:index' %}"> Lending Library</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'products:products' %}">Products</a></li>
            <li><a href="{% url 'products:my_products' %}">MyLibrary</a></li>
            <li><a href="{% url 'products:index' %}">Things Borrowed</a></li>
            <li><a href="{% url 'products:index' %}">Things Loaned</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nsv-collapse -->

    </div>
  </nav>

  <div class="container">

    <div class="page-header">
      {% block header %}{% endblock header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>

  </div> <!-- /container -->

  </body>
</html>

<footer>
  <p><a href="https://www.linkedin.com/in/josh-d-souza-915b2543" target="_blank" rel="noopener noreferrer">Creator: Josh D'Souza</a></p>
</footer>

products/templates/products/borrow_product.html
{% extends "products/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Borrow a product:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'products:borrow_product' product.id %}" method='post' class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">save changes</button>
    {% endbuttons %}

  </form>

{% endblock content %}

products/templates/products/index.html
{% extends "products/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Browse available books.</h1>
  </div>
{% endblock header %}

{% block content %}
  <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to advertise books you have available to lend.
  </h2>
  <h2>
    Lending Library helps you find local lenders willing to let you borrow books you'd like to read.
  </h2>
{% endblock content %}

products/templates/products/my_products.html
{% extends "products/base.html" %}

{% block header %}
  <h1>My Products</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for product in products %}
      <li>
        <h3>
          <a href="{% url 'products:product' product.id %}">{{ product }}</a> {{ product.date_added|date:'M d, Y H:i'}}
        </h3>
      </li>
    {% empty %}
      <li>No products have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'products:new_product' %}">Add a new product:</a></h3>

{% endblock content %}

products/templates/products/new_product.html
{% extends "products/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new product:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'products:new_product' %}" method='post' class="form">

  	{% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">add product</button>
    {% endbuttons %}

  </form>

{% endblock content %}

products/templates/products/product.html
{% extends 'products/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>{{ product }}</h2>
{% endblock header %}

{% block content %}

  <p>Product: {{ product }}</p>
  <p>Type: {{ product.product_type }}</p>
  <p>Description: {{product.description }}</p>
  <p>Owner: {{product.owner }}</p>

  {% buttons %}
    <button name="submit" class="btn btn-primary"><a href="{% url 'products:borrow_product' product.id %}">borrow product</a></button>
  {% endbuttons %}

  <!--p>
    <a href="{% url 'products:borrow_product' product.id %}">borrow product</a>
  </p-->

  {% for entry in entries %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ entry.date_added|date:'M d, Y H:i'}}
          <small>
            <a href="https://www.google.com">edit entry</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ entry.text|linebreaks }}
      </div>
    </div> <!-- panel --> 

  {% empty %}
    	There are no entries for this product yet.
  {% endfor %}

{% endblock content %}	

products/templates/products/products.html
{% extends "products/base.html" %}

{% block header %}
  <h1>Products</h1>
{% endblock header %}

{% block content %}

  <ul>
  	{% for product in products %}
  	  <li>
        <h3>
  	  	  <a href="{% url 'products:product' product.id %}">{{ product }}</a> {{ product.date_added|date:'M d, Y H:i'}}
        </h3>
  	  </li>
  	{% empty %}
  	  <li>No products have been added yet.</li>
  	{% endfor %}
  </ul>

  <h3><a href="{% url 'products:new_product' %}">Add a new product:</a></h3>

{% endblock content %}

users/templates/users/login.html
{% extends "products/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'products:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "products/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
	{% csrf_token %}
	{{ form.as_p }}

	<button name="submit">register</button>
	<input type="hidden" name="next" value="{% url 'products:index' %}" />
  </form>

{% endblock content %}